DROP DATABASE IF EXISTS auth;
CREATE DATABASE IF NOT EXISTS auth;
USE auth;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user
(id VARCHAR(32) PRIMARY KEY,
pwd VARCHAR(256),
salt VARCHAR(128));

